CREATE SCHEMA "EYSCHEMA";

CREATE TABLE "EYSCHEMA"."TBL_CITY" (
	cityid               INTEGER GENERATED ALWAYS AS IDENTITY  NOT NULL,
	citycode             VARCHAR(4)   NOT NULL,
	cityname             VARCHAR(50)   NOT NULL,
	CONSTRAINT "PK_TBL_CITY" PRIMARY KEY ( cityid )
 );

CREATE TABLE "EYSCHEMA"."TBL_COUNTRY" (
	countryid            INTEGER GENERATED ALWAYS AS IDENTITY  NOT NULL,
	countrycode          VARCHAR(3)   NOT NULL,
	countryname          VARCHAR(50)   NOT NULL,
	CONSTRAINT "PK_TBL_COUNTRY" PRIMARY KEY ( countryid )
 );

CREATE TABLE "EYSCHEMA"."TBL_USERS" (
	userid               INTEGER GENERATED ALWAYS AS IDENTITY  NOT NULL,
	username             VARCHAR(50)   NOT NULL,
	usermail             VARCHAR(50)   NOT NULL UNIQUE,
	userpasswd           VARCHAR(100)   NOT NULL,
	datecreation         TIMESTAMP   NOT NULL,
	dateupdate           TIMESTAMP   NOT NULL,
	datelastlogin        TIMESTAMP   ,
	isactive             VARCHAR(1)   NOT NULL,
	tokensession         CLOB(200)   ,
	useruuid             VARCHAR(64)   ,
	CONSTRAINT "PK_TBL_USER" PRIMARY KEY ( userid )
 );

CREATE TABLE "EYSCHEMA"."TBL_PHONES" (
	phoneid              INTEGER GENERATED ALWAYS AS IDENTITY  NOT NULL,
	"PHONENUMBER"        INTEGER   NOT NULL,
	"COUNTRYID"          INTEGER   NOT NULL,
	"CITYID"             INTEGER   NOT NULL,
	"USERID"             INTEGER   NOT NULL,
	CONSTRAINT "PK_TBL_PHONES" PRIMARY KEY ( phoneid )
 );

CREATE INDEX "FK_TBL_PHONES_TBL_CITY_INDEX_7" ON "EYSCHEMA"."TBL_PHONES" ( "CITYID" );

CREATE INDEX "FK_TBL_PHONES_TBL_COUNTRY_INDEX_7" ON "EYSCHEMA"."TBL_PHONES" ( "COUNTRYID" );

CREATE INDEX "FK_TBL_PHONES_TBL_USERS_INDEX_6" ON "EYSCHEMA"."TBL_PHONES" ( "USERID" );

ALTER TABLE "EYSCHEMA"."TBL_PHONES" ADD CONSTRAINT "FK_TBL_PHONES_TBL_COUNTRY" FOREIGN KEY ( "COUNTRYID" ) REFERENCES "EYSCHEMA"."TBL_COUNTRY"( countryid ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "EYSCHEMA"."TBL_PHONES" ADD CONSTRAINT "FK_TBL_PHONES_TBL_CITY" FOREIGN KEY ( "CITYID" ) REFERENCES "EYSCHEMA"."TBL_CITY"( cityid ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "EYSCHEMA"."TBL_PHONES" ADD CONSTRAINT "FK_TBL_PHONES_TBL_USERS" FOREIGN KEY ( "USERID" ) REFERENCES "EYSCHEMA"."TBL_USERS"( userid ) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMENT ON TABLE "EYSCHEMA"."TBL_CITY" IS 'table for cities';

COMMENT ON TABLE "EYSCHEMA"."TBL_COUNTRY" IS 'Table for countries';

COMMENT ON TABLE "EYSCHEMA"."TBL_USERS" IS 'table for users';
